### ISSUE TITLE
About environment

### ISSUE THREAD

**Issue by YuehengLuo** [ai-med/StablePose#5]
Hi!

Thank you for your great work! I would like to know which version of MMpose you are using. I am encountering a version conflict while reproducing it. I am currently using MMpose 0.29.0, which corresponds to MMTrack 0.14.0. MMTrack 0.14.0 requires SciPy <= 1.7.3, but scikit-image 0.20.0 requires SciPy < 1.9.2, >= 1.8. This creates an incompatibility when I run your script:

```python
eval_pose.py --config_model configs/stable_pose/humanart.yaml --ckpt experiments/stable_pose/run_name/final.pth --scale 7.5
```
Could you please provide some guidance on resolving this issue?

**Comment by farthjun** [comment]
@YuehengLuo Hi and thanks for your interest in our work. To solve this, pls just remove MMTrack since it's not needed in this project, but I think it's automatically installed somewhere. For MMPose, 0.29.0 is the one we used.

**Comment by YuehengLuo** [comment]
Thanks! I will try it.
