### ISSUE TITLE
Error in evaluation

### ISSUE THREAD

**Issue by deguchihiroyuki** [ai-med/StablePose#6]
Hi!
I have run evaluation
```powershell
eval_pose.py --config_model configs/stable_pose/humanart.yaml --ckpt experiments/stable_pose/run_name/final.pth --scale 7.5
``` 
and have an error as below.
```powershell
Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel
``` 
Although I have run
```powershell
python prepare_weights.py models/v1-5-pruned.ckpt configs/stable_pose/humanart.yaml models/init_stable_pose.ckpt
``` 
 and downloaded humanart.pth from the GoogleDrive and set it as the final.pth.

and also I have an error as below
```powershell

> `Traceback (most recent call last):
  File "/data/xx/StablePose/eval_pose.py", line 330, in <module>
    main()
  File "/data/xx/StablePose/eval_pose.py", line 206, in main
    metrics_calculator=instantiate_from_config(metrics_config.metrics)
  File "/data/xx/StablePose/ldm/util.py", line 83, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/data/xx/StablePose/utils/metrics/metric_main.py", line 23, in __init__
    self.pose_metrics_calculator=PoseMetrics(self.device,**self.pose)
  File "/data/ixx/StablePose/utils/metrics/pose_metrics.py", line 23, in __init__
    self.mmpose_model=init_model(mmpose_config_file,mmpose_checkpoint_file, device=self.device)
  File "/usr/local/lib/python3.10/site-packages/mmpose/apis/inference.py", line 104, in init_model
    model = build_pose_estimator(config.model)
  File "/usr/local/lib/python3.10/site-packages/mmpose/models/builder.py", line 35, in build_pose_estimator
    return POSE_ESTIMATORS.build(cfg)
  File "/usr/local/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'AssociativeEmbedding is not in the mmpose::model registry. Please check whether the value of `AssociativeEmbedding` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'`
``` 

 Could you please provide some guidance on resolving these problems?

**Comment by farthjun** [comment]
Hi @deguchihiroyuki, thanks for your interest in our work.

The first error `Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel` is actually a warning but not an error, and this can be ignored.

For your second error, I think it's about the mmpose. Would you pls tell me the version of your installed mmpose?

**Comment by deguchihiroyuki** [comment]
Thank you for your kind response!
I use the version below.
mmpose==1.3.2
mmcv==2.1.0

**Comment by farthjun** [comment]
Hi, thanks for the reply. The recommended version of mmpose is 0.29.0, and 1.6.2 for mmcv-full.

You might install via:
`mim install "mmpose==0.29.0"`
`mim install "mmcv-full==1.6.2"`

And thanks for raising the discussion. We'll update the recommended mmpose/mmcv version to our README.

**Comment by deguchihiroyuki** [comment]
Thank you! I will try it.
Incidentlly, I want to ask roughly how long it takes to run
```powershell
python train.py --config configs/stable_pose/humanart.yaml --max_epochs 1 --control_ckpt models/init_stable_pose.ckpt --devices 2 --scale_lr false
``` 
and how many epochs it takes to run?

**Comment by farthjun** [comment]
We trained for 10 epochs on Human-Art, which will take about 14 hours to train when using 2 A100(40GB) GPUs.

**Comment by deguchihiroyuki** [comment]
Thank you! I have succeeded in running the evaluation code using the above version.
Excuse me, just one more question.
Could you please tell me the correspondence between joints and colors for the input 2D keypoints?

**Comment by farthjun** [comment]
Hi, we followed [HumanSD](https://github.com/IDEA-Research/HumanSD) for the joints and colors of keypoints. You might want to refer to this [function](https://github.com/ai-med/StablePose/blob/main/ldm/data/dataset_pose.py#L73) for more details.
